### YamlMime:ManagedReference
items:
- uid: System.StackOverflowException
  id: StackOverflowException
  children:
  - System.StackOverflowException.#ctor
  - System.StackOverflowException.#ctor(System.String)
  - System.StackOverflowException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: StackOverflowException
  nameWithType: StackOverflowException
  fullName: System.StackOverflowException
  type: Class
  summary: "Eccezione generata quando si verifica un overflow dello stack di esecuzione a perché contiene troppe chiamate a metodi annidate. Questa classe non può essere ereditata."
  remarks: "StackOverflowException viene generata per errori di overflow dello stack di esecuzione, in genere in caso di ricorsione troppo profonda o illimitata.       StackOverflowException utilizza HRESULT COR_E_STACKOVERFLOW, con valore 0x800703E9. Il <xref:System.Reflection.Emit.OpCodes.Localloc>istruzione di linguaggio intermedio (IL) genera StackOverflowException.</xref:System.Reflection.Emit.OpCodes.Localloc> Per un elenco di valori di proprietà iniziali per un oggetto StackOverflowException, vedere il <xref:System.StackOverflowException.%23ctor%2A>costruttori.</xref:System.StackOverflowException.%23ctor%2A>      ## Considerazioni sulla versione di .NET Framework 1.0 e 1.1, è possibile intercettare un oggetto StackOverflowException (ad esempio, per ripristinare una ricorsione illimitata). A partire da .NET Framework 2.0, è possibile intercettare un oggetto StackOverflowException con un `try` / `catch` blocco e il processo corrispondente viene interrotto per impostazione predefinita. Di conseguenza, è consigliabile scrivere il codice per rilevare ed evitare un overflow dello stack. Ad esempio, se l&quot;applicazione dipende dalla ricorsione, utilizzare un contatore o una condizione di stato per terminare il ciclo ricorsivo. L&quot;esempio seguente usa un contatore per assicurarsi che il numero di ricorsiva chiama per il `Execute` metodo non superano un valore massimo definito dalla costante MAX_RECURSIVE_CALLS.       [!code-vb[System.StackOverflowException.Class#1](~/add/codesnippet/visualbasic/t-system.stackoverflowex_1.vb)][!code-cs[System.StackOverflowException.Class#1](~/add/codesnippet/csharp/t-system.stackoverflowex_1.cs) ]       >  [!NOTE] > applicazione il <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>attributo a un metodo che genera un StackOverflowException non ha alcun effetto.</xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>   È ancora non è possibile gestire l&quot;eccezione dal codice utente.       Se l&quot;app ospita common language runtime (CLR), è possibile specificare che CLR deve scaricare il dominio dell&quot;applicazione in cui si verifica l&quot;eccezione di overflow dello stack e proseguire il processo corrispondente. Per ulteriori informazioni, vedere [interfaccia ICLRPolicyManager](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class StackOverflowException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor
  id: '#ctor'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.StackOverflowException&quot;> </xref> (classe), l&quot;impostazione della <xref:System.Exception.Message*>proprietà della nuova istanza di un messaggio fornito dal sistema che descrive l&quot;errore, ad esempio &quot;l&quot;operazione ha causato un overflow dello stack&quot;.</xref:System.Exception.Message*> Questo messaggio prende in considerazione le impostazioni cultura correnti."
  remarks: "Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore localizzato. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException ();
    parameters: []
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.StackOverflowException&quot;> </xref> classe con un messaggio di errore specificato."
  remarks: "Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Un riferimento null (`Nothing` in Visual Basic). |   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Oggetto <xref:System.String>che descrive l&quot;errore.</xref:System.String> Il contenuto del messaggio deve essere facilmente comprensibile. Il chiamante del costruttore è necessario per garantire che la stringa sia stata localizzata per la lingua corrente."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.StackOverflowException&quot;> </xref> classe con un messaggio di errore specificato e un riferimento all&quot;eccezione interna che è la causa dell&quot;eccezione corrente."
  remarks: "Un&quot;eccezione generata come risultato diretto di un&quot;eccezione precedente può includere un riferimento all&quot;eccezione precedente nella <xref:System.Exception.InnerException%2A>proprietà.</xref:System.Exception.InnerException%2A> Il <xref:System.Exception.InnerException%2A>proprietà restituisce lo stesso valore passato al costruttore o un riferimento null (`Nothing` in Visual Basic) se il <xref:System.Exception.InnerException%2A>proprietà non fornisce il valore di eccezione interna al costruttore.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Il riferimento all&quot;eccezione interna. |   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio di errore che spiega il motivo dell&quot;eccezione."
    - id: innerException
      type: System.Exception
      description: "Eccezione che è la causa dell&quot;eccezione corrente. Se il `innerException` parametro non è un riferimento null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> in Visual Basic), l&quot;eccezione corrente viene generata in un <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blocco che gestisce l&quot;eccezione interna."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.StackOverflowException.#ctor
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
- uid: System.StackOverflowException.#ctor(System.String)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.StackOverflowException.#ctor*
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException
  nameWithType: StackOverflowException.StackOverflowException
